# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.exams = QtWidgets.QWidget()
        self.exams.setObjectName("exams")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.exams)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget.addTab(self.exams, "")
        self.templates = QtWidgets.QWidget()
        self.templates.setObjectName("templates")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.templates)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.templateListView = QtWidgets.QListView(self.templates)
        self.templateListView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.templateListView.setObjectName("templateListView")
        self.horizontalLayout_3.addWidget(self.templateListView)
        self.textEdit = QtWidgets.QTextEdit(self.templates)
        self.textEdit.setEnabled(False)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.tabWidget.addTab(self.templates, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTemplate = QtWidgets.QMenu(self.menubar)
        self.menuTemplate.setObjectName("menuTemplate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFileExit = QtWidgets.QAction(MainWindow)
        self.actionFileExit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionFileExit.setObjectName("actionFileExit")
        self.actionTemplateOpen = QtWidgets.QAction(MainWindow)
        self.actionTemplateOpen.setObjectName("actionTemplateOpen")
        self.menuFile.addAction(self.actionFileExit)
        self.menuTemplate.addAction(self.actionTemplateOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTemplate.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.actionFileExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automatic Exams Reader"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exams), _translate("MainWindow", "Exams"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.templates), _translate("MainWindow", "Templates"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTemplate.setTitle(_translate("MainWindow", "Template"))
        self.actionFileExit.setText(_translate("MainWindow", "Quit"))
        self.actionFileExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionTemplateOpen.setText(_translate("MainWindow", "Open"))

