# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.exams = QtWidgets.QWidget()
        self.exams.setObjectName("exams")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.exams)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.examListView = QtWidgets.QListView(self.exams)
        self.examListView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.examListView.setObjectName("examListView")
        self.horizontalLayout_2.addWidget(self.examListView)
        self.scrollArea = QtWidgets.QScrollArea(self.exams)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 480, 515))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.imageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imageLabel.setGeometry(QtCore.QRect(6, -4, 471, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.exams, "")
        self.templates = QtWidgets.QWidget()
        self.templates.setObjectName("templates")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.templates)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.templateListView = QtWidgets.QListView(self.templates)
        self.templateListView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.templateListView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.templateListView.setObjectName("templateListView")
        self.horizontalLayout_3.addWidget(self.templateListView)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.templates)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.templateTextEdit = QtWidgets.QTextEdit(self.tab)
        self.templateTextEdit.setEnabled(True)
        self.templateTextEdit.setGeometry(QtCore.QRect(0, -4, 481, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateTextEdit.sizePolicy().hasHeightForWidth())
        self.templateTextEdit.setSizePolicy(sizePolicy)
        self.templateTextEdit.setObjectName("templateTextEdit")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.templateViewLabel = QtWidgets.QLabel(self.tab_2)
        self.templateViewLabel.setGeometry(QtCore.QRect(0, 0, 481, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateViewLabel.sizePolicy().hasHeightForWidth())
        self.templateViewLabel.setSizePolicy(sizePolicy)
        self.templateViewLabel.setScaledContents(True)
        self.templateViewLabel.setObjectName("templateViewLabel")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.templates, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTemplate = QtWidgets.QMenu(self.menubar)
        self.menuTemplate.setObjectName("menuTemplate")
        self.menuExam = QtWidgets.QMenu(self.menubar)
        self.menuExam.setObjectName("menuExam")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFileExit = QtWidgets.QAction(MainWindow)
        self.actionFileExit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionFileExit.setObjectName("actionFileExit")
        self.actionTemplateOpen = QtWidgets.QAction(MainWindow)
        self.actionTemplateOpen.setObjectName("actionTemplateOpen")
        self.actionExamsImport = QtWidgets.QAction(MainWindow)
        self.actionExamsImport.setObjectName("actionExamsImport")
        self.menuFile.addAction(self.actionFileExit)
        self.menuTemplate.addAction(self.actionTemplateOpen)
        self.menuExam.addAction(self.actionExamsImport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTemplate.menuAction())
        self.menubar.addAction(self.menuExam.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        self.actionFileExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automatic Exams Reader"))
        self.imageLabel.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exams), _translate("MainWindow", "Exams"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "JSON"))
        self.templateViewLabel.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "GRAPHIC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.templates), _translate("MainWindow", "Templates"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTemplate.setTitle(_translate("MainWindow", "Template"))
        self.menuExam.setTitle(_translate("MainWindow", "Exams"))
        self.actionFileExit.setText(_translate("MainWindow", "Quit"))
        self.actionFileExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionTemplateOpen.setText(_translate("MainWindow", "Open"))
        self.actionExamsImport.setText(_translate("MainWindow", "Import"))
