TEMPLATES_LOADED = "app.templates.loaded"
EXAMS_LOADED = "app.exams.loaded"
TEMPLATE_DIALOG_PATH_KEY = "template.dialog.path"
EXAM_DIALOG_PATH_KEY = "exam.dialog.path"
PROCEED_TEMPLATE_DIALOG_PATH_KEY = "exam.proceed.dialog.path"
TEMPLATE_IMAGE_ZOOM = "template.image.zoom"
EXAM_IMAGE_ZOOM = "exam.image.zoom"
